### PR TITLE
Add Alpine variant

### PR DESCRIPTION
**Pull request by J0WI**
With #5 it's quite easy to add another variant

### CODE REVIEW

**Comment by LeoColomb** [comment]
Not perfect, but I will resolve the conflict on my side. 😉 
Thanks again!

**Comment by J0WI** [comment]
That was to quick, I just pushed https://github.com/J0WI/docker-yourls/commit/93cc704cef6d2cfef1ad367e4d84e070cad8b79f...

**Comment by LeoColomb** [comment]
I saw, no problem! 😄

**Comment by LeoColomb** [comment]
And sorry ^^

**Pull request merged**
